# Set the default framework logging (Spring, Tomcat, Hibernate) to INFO
logging.level.root=ERROR

# Ensure your custom application code is also locked to ERROR
logging.level.com.LocalService.lsp=ERROR

taraas.allowed-origins=https://taraas.com,https://www.taraas.com
