spring.application.name=lsp
spring.data.mongodb.database=Local_services

server.port=5000
logging.level.org.springframework.data.mongodb.core.MongoTemplate=ERROR

taraas.allowed-origins=http://localhost:3000,http://localhost:5173

